// Registering users

// Register a user
POST http://localhost:5000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "email": "user1@scotttest.com",
    "password": "TheSecondBestPassword"
}

###

// Access public resources
GET http://localhost:5000/api/test/all HTTP/1.1

###

// Access protected resources
GET http://localhost:5000/api/test/user HTTP/1.1

###

// Login with wrong password
POST http://localhost:5000/api/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "fsdfsfd"
}

###

// Login with correct password
POST http://localhost:5000/api/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "TheSecondBestPassword"
}

###

// Access protected resources
GET http://localhost:5000/api/test/user HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjkyOWRkN2U1YTg3ZDVhZjk3MzNhMCIsImlhdCI6MTY2MzY0MjIxNSwiZXhwIjoxNjYzNzI4NjE1fQ.ZAfZ7yvuOCCfJuHxd-DnEkjPV2Q6p3D1gdOhpMKc2GM

###

// Delete account
POST http://localhost:5000/api/test/delete-account HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjkyMTE2NWUxYTM2OTIyYzI2MTllMiIsImlhdCI6MTY2MzY0MDQwOSwiZXhwIjoxNjYzNzI2ODA5fQ.E7MFitx8ANcwTxmEpNOdVRt6ZStuUW8BS9UDsAK1Q6k
content-type: application/json

{
    "username": "user1"
}

###
